import { DamageType, SeverityLevel, RoadReport } from '../types';

export interface ExplanationResponse {
  explanation: string;
  suggestedAction: string;
  urgency: 'Immediate' | 'Elevated' | 'Standard' | 'Monitored';
}

export interface MaintenanceReportDetails {
  reportId: string;
  executiveSummary: string;
  subBaseRisk: string;
  recommendedMaterials: string[];
  trafficMitigation: string;
  estimatedWorkHours: string;
  disclaimer: string;
}

export interface DashboardInsights {
  summary: string;
  keyObservations: string[];
  strategicRecommendation: string;
}

export class GeminiService {
  /**
   * Request human-readable engineering explanation from backend Gemini API
   */
  public static async explainDamage(params: {
    damageType: DamageType;
    confidence: number;
    severity: SeverityLevel;
    priorityScore: number;
    roadName?: string;
    context?: string;
  }): Promise<ExplanationResponse> {
    try {
      const response = await fetch('/api/gemini/explain-damage', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(params),
      });

      if (!response.ok) {
        throw new Error(`Server returned ${response.status}`);
      }

      return await response.json();
    } catch (err) {
      console.warn('Using client fallback for Gemini explanation:', err);
      return {
        explanation: `${params.damageType} detected on ${params.roadName || 'the roadway'} with ${params.confidence}% confidence. Based on structural severity (${params.severity}) and traffic flow risk, this defect creates an active driving hazard.`,
        suggestedAction: params.severity === 'Critical' || params.priorityScore >= 80
          ? 'Dispatch emergency asphalt cold-patch crew within 24 hours to prevent tire blowouts.'
          : 'Schedule standard surface sealing and compaction in upcoming weekly maintenance cycle.',
        urgency: params.severity === 'Critical' ? 'Immediate' : params.severity === 'High' ? 'Elevated' : 'Standard',
      };
    }
  }

  /**
   * Request structured civil engineering report from backend Gemini API
   */
  public static async generateMaintenanceReport(report: RoadReport): Promise<MaintenanceReportDetails> {
    try {
      const response = await fetch('/api/gemini/generate-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          reportId: report.id,
          damageType: report.damageType,
          confidence: report.confidence,
          severity: report.severity,
          priorityScore: report.priorityScore,
          roadName: report.roadName,
          latitude: report.latitude,
          longitude: report.longitude,
          reportCount: report.reportCount,
          description: report.description,
        }),
      });

      if (!response.ok) {
        throw new Error(`Server returned ${response.status}`);
      }

      return await response.json();
    } catch (err) {
      console.warn('Using client fallback for Gemini maintenance report:', err);
      return {
        reportId: report.id,
        executiveSummary: `Engineering assessment for RoadGuard incident ${report.id}. Defect confirmed as ${report.damageType} on ${report.roadName}. Priority is computed at ${report.priorityScore}/100 with ${report.reportCount} combined community reports.`,
        subBaseRisk: report.severity === 'Critical'
          ? 'Severe moisture penetration through cracked asphalt wearing layer into granular base course, causing progressive subgrade subsidence.'
          : 'Surface-layer distress currently contained; prompt preventative sealing will avert structural base breakdown.',
        recommendedMaterials: report.damageType.toLowerCase().includes('crack')
          ? ['Hot-pour polymer-modified asphalt crack sealant (ASTM D6690)', 'Hot-compressed air lance', 'Mineral filler aggregate']
          : ['Hot-mix asphalt (HMA) Class 200 Surface Course', 'Bituminous tack coat emulsion (SS-1h)', 'Vibratory plate compactor or 3-ton roller'],
        trafficMitigation: report.priorityScore > 75
          ? 'Lane closure with electronic directional arrow board and safety channelizing cones during off-peak hours (09:30 - 15:30).'
          : 'Rolling temporary work zone with high-visibility vehicle beacon and flagger support.',
        estimatedWorkHours: report.priorityScore > 80 ? '3 - 5 hours' : '1.5 - 3 hours',
        disclaimer: 'This document is generated by RoadGuard AI as decision support. Final authorization requires field sign-off by a certified municipal engineer.',
      };
    }
  }

  /**
   * Request executive insights for admin dashboard
   */
  public static async getDashboardInsights(params: {
    totalReports: number;
    criticalCount: number;
    resolvedCount: number;
    topDamageType: string;
    roadHealthScore: number;
  }): Promise<DashboardInsights> {
    try {
      const response = await fetch('/api/gemini/dashboard-insights', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(params),
      });

      if (!response.ok) {
        throw new Error(`Server returned ${response.status}`);
      }

      return await response.json();
    } catch (err) {
      console.warn('Using client fallback for Gemini dashboard insights:', err);
      return {
        summary: `Municipal Road Health currently scores ${params.roadHealthScore}/100. Prompt crew allocation to ${params.criticalCount} critical structural alerts is paramount to keep arterial corridors safe.`,
        keyObservations: [
          `${params.criticalCount} high-risk hazards have priority scores exceeding 80/100 and need rapid patch crews.`,
          `${params.resolvedCount} maintenance tasks have been verified with before/after documentation.`,
          `${params.topDamageType} remains the most prevalent pavement distress mode across the district.`,
        ],
        strategicRecommendation: 'Mobilize preventative crack sealing squads before heavy seasonal rainfall to inhibit base erosion.',
      };
    }
  }
}
