import { RoadReport, RoadHealthMetrics, User } from '../types';

const STORAGE_KEY = 'roadguard_reports_v3';

export const INITIAL_REPORTS: RoadReport[] = [
  {
    id: 'RG-2026-081',
    userId: 'usr_citizen_1',
    userName: 'Ravi Kumar',
    reportedBy: 'Ravi Kumar',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9891,
    longitude: 82.2475,
    roadName: 'Main Road, Kakinada',
    city: 'Kakinada',
    district: 'Kakinada District',
    state: 'Andhra Pradesh',
    description: 'Deep tire-damaging cavity pothole near central commercial junction. Heavy traffic with two-wheelers and auto-rickshaws.',
    trafficLevel: 'Heavy Arterial',
    damageType: 'Pothole',
    confidence: 94,
    severity: 'High',
    priorityScore: 87,
    boundingBoxes: [
      {
        id: 'box_081_1',
        label: 'Pothole',
        confidence: 94,
        x1: 28,
        y1: 46,
        x2: 74,
        y2: 84,
        estimatedAreaSqM: 0.85,
        estimatedDepthCm: 7.2,
      },
    ],
    status: 'Under Review',
    reportCount: 6,
    duplicateReportIds: ['RG-2026-081-dup1', 'RG-2026-081-dup2'],
    createdAt: '2026-09-28T09:15:00.000Z',
    reportedDate: '2026-09-28',
    updatedAt: '2026-09-29T14:20:00.000Z',
    aiExplanation: 'RoadGuard detected a large pothole with 94% confidence. Based on the configured RoadGuard scoring factors, the issue is classified as high priority and should be inspected.',
    suggestedAction: 'Schedule emergency asphalt cold patch inspection followed by permanent subgrade compaction.',
    recommendedAction: 'Schedule emergency asphalt cold patch inspection followed by permanent subgrade compaction.',
    urgency: 'Elevated',
  },
  {
    id: 'RG-2026-080',
    userId: 'usr_citizen_coll',
    userName: 'K. Somaraju',
    reportedBy: 'K. Somaraju',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9605,
    longitude: 82.2355,
    roadName: 'Collectorate Road, Kakinada',
    city: 'Kakinada',
    district: 'Collectorate Administrative Zone',
    state: 'Andhra Pradesh',
    description: 'Multiple longitudinal fissures and cavity potholes along the main district administrative avenue.',
    trafficLevel: 'Heavy Arterial',
    damageType: 'Pothole',
    confidence: 93,
    severity: 'High',
    priorityScore: 84,
    boundingBoxes: [
      {
        id: 'box_080_1',
        label: 'Pothole',
        confidence: 93,
        x1: 25,
        y1: 44,
        x2: 70,
        y2: 82,
        estimatedAreaSqM: 0.75,
        estimatedDepthCm: 6.5,
      },
    ],
    status: 'Reported',
    reportCount: 5,
    createdAt: '2026-09-29T08:10:00.000Z',
    reportedDate: '2026-09-29',
    updatedAt: '2026-09-29T08:10:00.000Z',
    aiExplanation: 'Pothole cavity identified near Collectorate junction with heavy government transit and bus movement.',
    suggestedAction: 'Expedite road crew deployment for cold asphalt patching and surface leveling.',
    recommendedAction: 'Expedite road crew deployment for cold asphalt patching and surface leveling.',
    urgency: 'Elevated',
  },
  {
    id: 'RG-2026-079',
    userId: 'usr_citizen_2',
    userName: 'P. Anitha',
    reportedBy: 'P. Anitha',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9935,
    longitude: 82.2410,
    roadName: 'College Road, Kakinada',
    city: 'Kakinada',
    district: 'Kakinada District',
    state: 'Andhra Pradesh',
    description: 'Interconnected alligator cracking pattern near engineering college transit gate.',
    trafficLevel: 'High',
    damageType: 'Alligator Crack',
    confidence: 91,
    severity: 'Critical',
    priorityScore: 89,
    boundingBoxes: [
      {
        id: 'box_079_1',
        label: 'Alligator Crack',
        confidence: 91,
        x1: 18,
        y1: 34,
        x2: 82,
        y2: 88,
        estimatedAreaSqM: 2.4,
        estimatedDepthCm: 3.8,
      },
    ],
    status: 'In Progress',
    reportCount: 4,
    createdAt: '2026-09-26T11:30:00.000Z',
    reportedDate: '2026-09-26',
    updatedAt: '2026-09-29T10:00:00.000Z',
    assignedEngineer: 'K. S. Rao, Executive Engineer',
    maintenanceCrew: 'KMC Pavement Unit #1',
    engineerRemarks: 'Sub-base fatigue confirmed. Cold milling and Bituminous Concrete (BC) resurfacing ordered.',
    aiExplanation: 'Severe structural fatigue alligator cracking detected. Moisture seepage during monsoon could cause base subsidence.',
    suggestedAction: 'Milling 40mm wearing layer and laying dense bituminous macadam overlay.',
    recommendedAction: 'Milling 40mm wearing layer and laying dense bituminous macadam overlay.',
    urgency: 'Immediate',
  },
  {
    id: 'RG-2026-074',
    userId: 'usr_citizen_3',
    userName: 'S. Naidu',
    reportedBy: 'S. Naidu',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9740,
    longitude: 82.2280,
    roadName: 'NH-216 Corridor (Bypass)',
    city: 'Kakinada',
    district: 'Kakinada District',
    state: 'Andhra Pradesh',
    description: 'Eroded asphalt shoulder and edge drop-off along the high-speed highway curve.',
    trafficLevel: 'Heavy Arterial',
    damageType: 'Damaged Road Edge',
    confidence: 93,
    severity: 'High',
    priorityScore: 78,
    boundingBoxes: [
      {
        id: 'box_074_1',
        label: 'Damaged Road Edge',
        confidence: 93,
        x1: 68,
        y1: 30,
        x2: 96,
        y2: 92,
        estimatedAreaSqM: 1.6,
        estimatedDepthCm: 8.0,
      },
    ],
    status: 'Under Review',
    reportCount: 3,
    createdAt: '2026-09-25T14:45:00.000Z',
    reportedDate: '2026-09-25',
    updatedAt: '2026-09-28T16:10:00.000Z',
    assignedEngineer: 'K. S. Rao, Executive Engineer',
    engineerRemarks: 'Shoulder gravel backfilling and asphalt edge wedge compaction scheduled.',
    aiExplanation: 'Shoulder edge drop exceeding 8 cm creates vehicle rollover and tyre damage hazards for high-speed traffic.',
    suggestedAction: 'Grade and compact granular sub-base and seal edge with hot bitumen tack coat.',
    recommendedAction: 'Grade and compact granular sub-base and seal edge with hot bitumen tack coat.',
    urgency: 'Elevated',
  },
  {
    id: 'RG-2026-068',
    userId: 'usr_citizen_4',
    userName: 'K. Lakshmi',
    reportedBy: 'K. Lakshmi',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1494783367193-149034c05e8f?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1494783367193-149034c05e8f?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9950,
    longitude: 82.2380,
    roadName: 'Market Road, Kakinada',
    city: 'Kakinada',
    district: 'Main Bazaar',
    state: 'Andhra Pradesh',
    description: 'Pothole in the vegetable market lane repaired and verified by municipal crew.',
    trafficLevel: 'Moderate',
    damageType: 'Pothole',
    confidence: 95,
    severity: 'High',
    priorityScore: 82,
    boundingBoxes: [
      {
        id: 'box_068_1',
        label: 'Pothole',
        confidence: 95,
        x1: 30,
        y1: 45,
        x2: 70,
        y2: 80,
        estimatedAreaSqM: 0.65,
        estimatedDepthCm: 6.0,
      },
    ],
    status: 'Repaired',
    reportCount: 5,
    createdAt: '2026-09-20T08:00:00.000Z',
    reportedDate: '2026-09-20',
    updatedAt: '2026-09-27T17:30:00.000Z',
    assignedEngineer: 'K. S. Rao, Executive Engineer',
    maintenanceCrew: 'KMC Rapid Patch Unit',
    engineerRemarks: 'Cold-mix asphalt patch laid and compacted with vibratory roller. Surface level restored.',
    repairImageUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=1000&q=80',
    resolvedDate: '2026-09-27T17:30:00.000Z',
    aiExplanation: 'Repaired: Pothole defect repaired with hot-mix asphalt and vibratory compaction.',
    suggestedAction: 'Repair verified. Pavement condition index restored.',
    recommendedAction: 'Repair verified. Pavement condition index restored.',
    urgency: 'Standard',
  },
  {
    id: 'RG-2026-062',
    userId: 'usr_citizen_5',
    userName: 'V. Prasad',
    reportedBy: 'V. Prasad',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9650,
    longitude: 82.2610,
    roadName: 'Port Road, Kakinada',
    city: 'Kakinada',
    district: 'Industrial Port Sector',
    state: 'Andhra Pradesh',
    description: 'Heavy trailer traffic has caused surface raveling, loose aggregates, and wheel rutting.',
    trafficLevel: 'High',
    damageType: 'Damaged Road Surface',
    confidence: 88,
    severity: 'Medium',
    priorityScore: 56,
    boundingBoxes: [
      {
        id: 'box_062_1',
        label: 'Damaged Road Surface',
        confidence: 88,
        x1: 22,
        y1: 42,
        x2: 78,
        y2: 78,
        estimatedAreaSqM: 1.8,
        estimatedDepthCm: 2.8,
      },
    ],
    status: 'Under Review',
    reportCount: 2,
    createdAt: '2026-09-27T13:10:00.000Z',
    reportedDate: '2026-09-27',
    updatedAt: '2026-09-28T09:00:00.000Z',
    aiExplanation: 'Surface raveling and aggregate detachment observed on port heavy freight route.',
    suggestedAction: 'Micro-surfacing seal coat recommended to restore skid resistance.',
    recommendedAction: 'Micro-surfacing seal coat recommended to restore skid resistance.',
    urgency: 'Standard',
  },
  {
    id: 'RG-2026-055',
    userId: 'usr_citizen_6',
    userName: 'Ch. Srinivas',
    reportedBy: 'Ch. Srinivas',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9820,
    longitude: 82.2530,
    roadName: 'Residential Road, Kakinada',
    city: 'Kakinada',
    district: 'Suryanarayana Puram',
    state: 'Andhra Pradesh',
    description: 'Transverse thermal shrinkage crack across residential lane.',
    trafficLevel: 'Low',
    damageType: 'Transverse Crack',
    confidence: 90,
    severity: 'Low',
    priorityScore: 28,
    boundingBoxes: [
      {
        id: 'box_055_1',
        label: 'Transverse Crack',
        confidence: 90,
        x1: 15,
        y1: 52,
        x2: 88,
        y2: 64,
        estimatedAreaSqM: 0.45,
        estimatedDepthCm: 1.8,
      },
    ],
    status: 'Reported',
    reportCount: 1,
    createdAt: '2026-09-29T07:45:00.000Z',
    reportedDate: '2026-09-29',
    updatedAt: '2026-09-29T07:45:00.000Z',
    aiExplanation: 'Low-severity transverse shrinkage crack. Normal thermal pavement expansion/contraction.',
    suggestedAction: 'Apply hot-pour elastomeric sealant during routine cyclical maintenance.',
    recommendedAction: 'Apply hot-pour elastomeric sealant during routine cyclical maintenance.',
    urgency: 'Monitored',
  },
  {
    id: 'RG-2026-048',
    userId: 'usr_citizen_7',
    userName: 'M. Satyanarayana',
    reportedBy: 'M. Satyanarayana',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9870,
    longitude: 82.2440,
    roadName: 'Cinema Road, Kakinada',
    city: 'Kakinada',
    district: 'Kakinada City',
    state: 'Andhra Pradesh',
    description: 'Continuous longitudinal crack along construction joint line near cinema complex.',
    trafficLevel: 'Moderate',
    damageType: 'Longitudinal Crack',
    confidence: 89,
    severity: 'Medium',
    priorityScore: 48,
    boundingBoxes: [
      {
        id: 'box_048_1',
        label: 'Longitudinal Crack',
        confidence: 89,
        x1: 44,
        y1: 20,
        x2: 56,
        y2: 88,
        estimatedAreaSqM: 0.6,
        estimatedDepthCm: 2.1,
      },
    ],
    status: 'Reported',
    reportCount: 2,
    createdAt: '2026-09-28T14:10:00.000Z',
    reportedDate: '2026-09-28',
    updatedAt: '2026-09-28T14:10:00.000Z',
    aiExplanation: 'Longitudinal joint crack running parallel to traffic flow. Requires bituminous crack sealing before monsoon season.',
    suggestedAction: 'Rout and seal crack with ASTM D6690 hot-applied polymer sealant.',
    recommendedAction: 'Rout and seal crack with ASTM D6690 hot-applied polymer sealant.',
    urgency: 'Standard',
  },
  {
    id: 'RG-2026-044',
    userId: 'usr_citizen_8',
    userName: 'T. Bhavani',
    reportedBy: 'T. Bhavani',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9980,
    longitude: 82.2430,
    roadName: 'Bhanugudi Junction',
    city: 'Kakinada',
    district: 'Kakinada Central',
    state: 'Andhra Pradesh',
    description: 'Major traffic bottleneck pothole at the main signal junction causing severe two-wheeler skidding risk.',
    trafficLevel: 'Heavy Arterial',
    damageType: 'Pothole',
    confidence: 96,
    severity: 'Critical',
    priorityScore: 94,
    boundingBoxes: [
      {
        id: 'box_044_1',
        label: 'Pothole',
        confidence: 96,
        x1: 30,
        y1: 40,
        x2: 72,
        y2: 82,
        estimatedAreaSqM: 1.1,
        estimatedDepthCm: 8.5,
      },
    ],
    status: 'Reported',
    reportCount: 7,
    duplicateReportIds: ['RG-2026-044-dup1'],
    createdAt: '2026-09-29T10:15:00.000Z',
    reportedDate: '2026-09-29',
    updatedAt: '2026-09-29T10:15:00.000Z',
    aiExplanation: 'Critical road hazard: large, deep cavity situated in dense commuter intersection. Immediate hazard mitigation needed.',
    suggestedAction: 'Deploy emergency asphalt cold mix patch immediately, followed by permanent hot asphalt restoration.',
    recommendedAction: 'Deploy emergency asphalt cold mix patch immediately, followed by permanent hot asphalt restoration.',
    urgency: 'Immediate',
  },
  {
    id: 'RG-2026-039',
    userId: 'usr_citizen_9',
    userName: 'G. Venkatesh',
    reportedBy: 'G. Venkatesh',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9720,
    longitude: 82.2390,
    roadName: 'Jagannaickpur Bridge Approach',
    city: 'Kakinada',
    district: 'Jagannaickpur',
    state: 'Andhra Pradesh',
    description: 'Thermoplastic central divider and edge lane markings almost completely worn off.',
    trafficLevel: 'High',
    damageType: 'Faded Lane Marking',
    confidence: 87,
    severity: 'Low',
    priorityScore: 24,
    boundingBoxes: [
      {
        id: 'box_039_1',
        label: 'Faded Lane Marking',
        confidence: 87,
        x1: 45,
        y1: 25,
        x2: 55,
        y2: 85,
        estimatedAreaSqM: 0.9,
        estimatedDepthCm: 0.1,
      },
    ],
    status: 'Under Review',
    reportCount: 2,
    createdAt: '2026-09-27T08:30:00.000Z',
    reportedDate: '2026-09-27',
    updatedAt: '2026-09-27T08:30:00.000Z',
    aiExplanation: 'Thermoplastic reflective paint degraded on bridge approach corridor, causing poor night lane discipline.',
    suggestedAction: 'Repaint with retroreflective thermoplastic paint with glass bead dispersion.',
    recommendedAction: 'Repaint with retroreflective thermoplastic paint with glass bead dispersion.',
    urgency: 'Monitored',
  },
  {
    id: 'RG-2026-035',
    userId: 'usr_citizen_10',
    userName: 'D. Suresh',
    reportedBy: 'D. Suresh',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80',
    latitude: 17.0040,
    longitude: 82.2490,
    roadName: 'Ramanayyapeta Road',
    city: 'Kakinada',
    district: 'Ramanayyapeta',
    state: 'Andhra Pradesh',
    description: 'Cluster of fatigue alligator cracking along the municipal bus transit route.',
    trafficLevel: 'Moderate',
    damageType: 'Alligator Crack',
    confidence: 92,
    severity: 'High',
    priorityScore: 76,
    boundingBoxes: [
      {
        id: 'box_035_1',
        label: 'Alligator Crack',
        confidence: 92,
        x1: 20,
        y1: 35,
        x2: 80,
        y2: 85,
        estimatedAreaSqM: 1.9,
        estimatedDepthCm: 3.2,
      },
    ],
    status: 'In Progress',
    reportCount: 3,
    createdAt: '2026-09-25T16:20:00.000Z',
    reportedDate: '2026-09-25',
    updatedAt: '2026-09-29T11:00:00.000Z',
    assignedEngineer: 'K. S. Rao, Executive Engineer',
    maintenanceCrew: 'KMC Patch Team #2',
    engineerRemarks: 'Milling scheduled for tonight. Surface tack coat applied.',
    aiExplanation: 'Advanced fatigue cracking. Subgrade needs stabilization to avoid widespread cavity formation.',
    suggestedAction: 'Cold mill 50mm and overlay with hot mix bituminous concrete.',
    recommendedAction: 'Cold mill 50mm and overlay with hot mix bituminous concrete.',
    urgency: 'Elevated',
  },
  {
    id: 'RG-2026-028',
    userId: 'usr_citizen_11',
    userName: 'B. Apparao',
    reportedBy: 'B. Apparao',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=1000&q=80',
    latitude: 16.9790,
    longitude: 82.2360,
    roadName: 'Boat Club Road, Kakinada',
    city: 'Kakinada',
    district: 'Kakinada Lake Precinct',
    state: 'Andhra Pradesh',
    description: 'Road surface unraveling near tourism boat club entrance. Resurfaced and completed.',
    trafficLevel: 'Moderate',
    damageType: 'Damaged Road Surface',
    confidence: 90,
    severity: 'Medium',
    priorityScore: 52,
    boundingBoxes: [
      {
        id: 'box_028_1',
        label: 'Damaged Road Surface',
        confidence: 90,
        x1: 25,
        y1: 45,
        x2: 75,
        y2: 75,
        estimatedAreaSqM: 1.5,
        estimatedDepthCm: 2.2,
      },
    ],
    status: 'Repaired',
    reportCount: 3,
    createdAt: '2026-09-18T11:00:00.000Z',
    reportedDate: '2026-09-18',
    updatedAt: '2026-09-26T16:00:00.000Z',
    assignedEngineer: 'K. S. Rao, Executive Engineer',
    maintenanceCrew: 'KMC Tourism Sector Crew',
    repairImageUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=1000&q=80',
    resolvedDate: '2026-09-26T16:00:00.000Z',
    aiExplanation: 'Repaired: Bituminous slurry seal completed across the boat club roadway section.',
    suggestedAction: 'Periodic annual resurfacing check.',
    recommendedAction: 'Periodic annual resurfacing check.',
    urgency: 'Standard',
  },
  {
    id: 'RG-2026-022',
    userId: 'usr_citizen_12',
    userName: 'N. Rajesh',
    reportedBy: 'N. Rajesh',
    userRole: 'citizen',
    imageUrl: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1000&q=80',
    image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1000&q=80',
    latitude: 17.0120,
    longitude: 82.2560,
    roadName: 'Sarpavaram Junction Road',
    city: 'Kakinada',
    district: 'Sarpavaram',
    state: 'Andhra Pradesh',
    description: 'Broken asphalt shoulder edge collapsing into side storm drainage ditch.',
    trafficLevel: 'High',
    damageType: 'Damaged Road Edge',
    confidence: 91,
    severity: 'High',
    priorityScore: 74,
    boundingBoxes: [
      {
        id: 'box_022_1',
        label: 'Damaged Road Edge',
        confidence: 91,
        x1: 70,
        y1: 32,
        x2: 95,
        y2: 90,
        estimatedAreaSqM: 1.3,
        estimatedDepthCm: 7.5,
      },
    ],
    status: 'In Progress',
    reportCount: 4,
    createdAt: '2026-09-26T09:40:00.000Z',
    reportedDate: '2026-09-26',
    updatedAt: '2026-09-29T12:30:00.000Z',
    assignedEngineer: 'K. S. Rao, Executive Engineer',
    maintenanceCrew: 'KMC Edge Reinforcement Unit',
    engineerRemarks: 'Retaining edge stones installed. Asphalt curb compaction in progress.',
    aiExplanation: 'Shoulder erosion into stormwater drainage ditch. Requires edge barrier stabilization.',
    suggestedAction: 'Install precast concrete curbs and compact asphalt wedge along shoulder.',
    recommendedAction: 'Install precast concrete curbs and compact asphalt wedge along shoulder.',
    urgency: 'Elevated',
  },
];

export class StorageService {
  public static getReports(): RoadReport[] {
    try {
      const data = localStorage.getItem(STORAGE_KEY);
      if (data) {
        return JSON.parse(data);
      }
    } catch (e) {
      console.error('Error reading localStorage reports:', e);
    }
    // Initialize with 12 default reports
    this.saveReports(INITIAL_REPORTS);
    return INITIAL_REPORTS;
  }

  public static saveReports(reports: RoadReport[]): void {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(reports));
    } catch (e) {
      console.error('Error saving localStorage reports:', e);
    }
  }

  public static addReport(report: RoadReport): RoadReport[] {
    const current = this.getReports();
    const updated = [report, ...current];
    this.saveReports(updated);
    return updated;
  }

  public static updateReport(id: string, updates: Partial<RoadReport>): RoadReport[] {
    const current = this.getReports();
    const updated = current.map((r) => {
      if (r.id === id) {
        return {
          ...r,
          ...updates,
          updatedAt: new Date().toISOString(),
        };
      }
      return r;
    });
    this.saveReports(updated);
    return updated;
  }

  public static deleteReport(id: string): RoadReport[] {
    const current = this.getReports();
    const updated = current.filter((r) => r.id !== id);
    this.saveReports(updated);
    return updated;
  }

  public static calculateRoadHealthMetrics(reports: RoadReport[]): RoadHealthMetrics {
    const totalPotholes = reports.filter((r) => r.damageType === 'Pothole').length;
    const totalCracks = reports.filter((r) =>
      ['Longitudinal Crack', 'Transverse Crack', 'Alligator Crack'].includes(r.damageType)
    ).length;
    const totalSurfaceDefects = reports.filter((r) =>
      ['Damaged Road Surface', 'Damaged Road Edge', 'Damaged Road Edges', 'Faded Lane Marking', 'Faded Lane Markings'].includes(
        r.damageType
      )
    ).length;
    const criticalIssues = reports.filter(
      (r) => r.severity === 'Critical' && r.status !== 'Repaired' && r.status !== 'Resolved'
    ).length;
    const resolvedLast30Days = reports.filter((r) => r.status === 'Repaired' || r.status === 'Resolved').length;

    // Road health penalty algorithm
    const activeReports = reports.filter((r) => r.status !== 'Repaired' && r.status !== 'Resolved');
    let penalty = 0;
    for (const r of activeReports) {
      if (r.severity === 'Critical') penalty += 5;
      else if (r.severity === 'High') penalty += 3;
      else if (r.severity === 'Medium') penalty += 1.5;
      else penalty += 0.5;
    }

    const overallScore = Math.min(Math.max(Math.round(100 - penalty), 40), 96);

    return {
      overallScore,
      totalPotholes,
      totalCracks,
      totalSurfaceDefects,
      criticalIssues,
      resolvedLast30Days,
      averageResolutionHours: 32,
    };
  }
}
